### ISSUE TITLE
Add some security

### ISSUE THREAD

**Issue by patfreeman** [ph1l/ocemr-appliance#2]
- Add authentication
- Hide passwords
- Other suggestions?

**Comment by bsmoliak** [comment]
Enforce password complexity and length

**Comment by patfreeman** [comment]
Probably a good idea, but might be a bit overzealous for the port 5000 service to configure the appliance.

**Comment by bsmoliak** [comment]
Point taken. I didn't mean to suggest anything cumbersome.
